// <auto-generated />
using System;
using IntegrationLibrary.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IntegrationLibrary.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
<<<<<<<< HEAD:PSW-projekat/hospital-be-main/src/IntegrationLibrary/Migrations/20221121213659_initial.Designer.cs
    [Migration("20221121213659_initial")]
========
    [Migration("20221121192316_initial")]
>>>>>>>> origin/feature-T9-accept_news:PSW-projekat/hospital-be-main/src/IntegrationLibrary/Migrations/20221121192316_initial.Designer.cs
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IntegrationLibrary.Core.Model.BloodBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BloodBanks");
                });

            modelBuilder.Entity("IntegrationLibrary.Core.Model.BloodRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BloodBankId")
                        .HasColumnType("int");

                    b.Property<int>("BloodQuantity")
                        .HasColumnType("int");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestState")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequiredForDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BloodRequests");
                });

            modelBuilder.Entity("IntegrationLibrary.Core.Model.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BloodBankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("_bloodBankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("_dateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Newses");
                });

            modelBuilder.Entity("IntegrationLibrary.Core.Model.ReportSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CalculationDays")
                        .HasColumnType("int");

                    b.Property<int>("CalculationMonths")
                        .HasColumnType("int");

                    b.Property<int>("CalculationYears")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryMonths")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryYears")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDeliveryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ReportSettings");
<<<<<<<< HEAD:PSW-projekat/hospital-be-main/src/IntegrationLibrary/Migrations/20221121213659_initial.Designer.cs
========

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalculationDays = 0,
                            CalculationMonths = 1,
                            CalculationYears = 0,
                            DeliveryDays = 0,
                            DeliveryMonths = 1,
                            DeliveryYears = 0,
                            StartDeliveryDate = new DateTime(2022, 11, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        });
>>>>>>>> origin/feature-T9-accept_news:PSW-projekat/hospital-be-main/src/IntegrationLibrary/Migrations/20221121192316_initial.Designer.cs
                });
#pragma warning restore 612, 618
        }
    }
}
